language: cpp
dist: xenial
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.11.0-xenial -y
  - sudo apt-get update

install:
  - sudo apt-get install qt511base qt511svg qt511-meta-minimal libgl1-mesa-dev
  - source /opt/qt511/bin/qt511-env.sh


script:
  - /opt/qt511/bin/qmake PREFIX=/usr
  - make
